version: "3.9"
   
services:  
  app:
    build: .
    container_name: app-django-challenge
    command: python manage.py runserver 0.0.0.0:8000
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./app:/app
    env_file:
      - ./.env
    ports:
      - "8080:8000"
    networks:
      - django-challenger

  db:
    container_name: db-django-challenge
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "challenge"
    volumes:
      - ./db/dev:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 24
    networks:
      - django-challenger

networks:
  django-challenger:
    name: django-challenger-dev
    driver: bridge



